// ⚠ 자동 생성 파일입니다. scripts/generateIconMap.mjs를 수정하세요.
export const WIDGET_BASE = "/icons/widgets";

export const ICON_MAP: Record<string, string> = {
  // ===== data =====
  "AggregateColumns": "/icons/widgets/data/AggregateColumns.svg",
  "Category-Data": "/icons/widgets/data/Category-Data.svg",
  "Colors": "/icons/widgets/data/Colors.svg",
  "Concatenate": "/icons/widgets/data/Concatenate.svg",
  "Continuize": "/icons/widgets/data/Continuize.svg",
  "Correlations": "/icons/widgets/data/Correlations.svg",
  "CreateClass": "/icons/widgets/data/CreateClass.svg",
  "CreateInstance": "/icons/widgets/data/CreateInstance.svg",
  "CSVFile": "/icons/widgets/data/CSVFile.svg",
  "DataInfo": "/icons/widgets/data/DataInfo.svg",
  "DataSampler": "/icons/widgets/data/DataSampler.svg",
  "DataSets": "/icons/widgets/data/DataSets.svg",
  "Discretize": "/icons/widgets/data/Discretize.svg",
  "EditDomain": "/icons/widgets/data/EditDomain.svg",
  "FeatureConstructor": "/icons/widgets/data/FeatureConstructor.svg",
  "FeatureStatistics": "/icons/widgets/data/FeatureStatistics.svg",
  "File": "/icons/widgets/data/File.svg",
  "GroupBy": "/icons/widgets/data/GroupBy.svg",
  "Impute": "/icons/widgets/data/Impute.svg",
  "Melt": "/icons/widgets/data/Melt.svg",
  "MergeData": "/icons/widgets/data/MergeData.svg",
  "Neighbors": "/icons/widgets/data/Neighbors.svg",
  "Normalize": "/icons/widgets/data/Normalize.svg",
  "Outliers": "/icons/widgets/data/Outliers.svg",
  "PaintData": "/icons/widgets/data/PaintData.svg",
  "PCA": "/icons/widgets/data/PCA.svg",
  "Pivot": "/icons/widgets/data/Pivot.svg",
  "Preprocess": "/icons/widgets/data/Preprocess.svg",
  "PurgeDomain": "/icons/widgets/data/PurgeDomain.svg",
  "PythonScript": "/icons/widgets/data/PythonScript.svg",
  "Random": "/icons/widgets/data/Random.svg",
  "Rank": "/icons/widgets/data/Rank.svg",
  "Save": "/icons/widgets/data/Save.svg",
  "SelectByDataIndex": "/icons/widgets/data/SelectByDataIndex.svg",
  "SelectColumns": "/icons/widgets/data/SelectColumns.svg",
  "SelectColumnsRandom": "/icons/widgets/data/SelectColumnsRandom.svg",
  "SelectRows": "/icons/widgets/data/SelectRows.svg",
  "Split": "/icons/widgets/data/Split.svg",
  "SQLTable": "/icons/widgets/data/SQLTable.svg",
  "Table": "/icons/widgets/data/Table.svg",
  "Transform": "/icons/widgets/data/Transform.svg",
  "Transpose": "/icons/widgets/data/Transpose.svg",
  "Unique": "/icons/widgets/data/Unique.svg",

  // ===== evaluate =====
  "CalibrationPlot": "/icons/widgets/evaluate/CalibrationPlot.svg",
  "Category-Evaluate": "/icons/widgets/evaluate/Category-Evaluate.svg",
  "ConfusionMatrix": "/icons/widgets/evaluate/ConfusionMatrix.svg",
  "FeatureAsPredictor": "/icons/widgets/evaluate/FeatureAsPredictor.svg",
  "LiftCurve": "/icons/widgets/evaluate/LiftCurve.svg",
  "ParameterFitter": "/icons/widgets/evaluate/ParameterFitter.svg",
  "PermutationPlot": "/icons/widgets/evaluate/PermutationPlot.svg",
  "Predictions": "/icons/widgets/evaluate/Predictions.svg",
  "ROCAnalysis": "/icons/widgets/evaluate/ROCAnalysis.svg",
  "TestLearners1": "/icons/widgets/evaluate/TestLearners1.svg",
  "TestLearners2": "/icons/widgets/evaluate/TestLearners2.svg",

  // ===== model =====
  "AdaBoost": "/icons/widgets/model/AdaBoost.svg",
  "CalibratedLearner": "/icons/widgets/model/CalibratedLearner.svg",
  "Category-Model": "/icons/widgets/model/Category-Model.svg",
  "CN2RuleInduction": "/icons/widgets/model/CN2RuleInduction.svg",
  "Constant": "/icons/widgets/model/Constant.svg",
  "CurveFit": "/icons/widgets/model/CurveFit.svg",
  "GradientBoosting": "/icons/widgets/model/GradientBoosting.svg",
  "KNN": "/icons/widgets/model/KNN.svg",
  "LinearRegression": "/icons/widgets/model/LinearRegression.svg",
  "LoadModel": "/icons/widgets/model/LoadModel.svg",
  "LogisticRegression": "/icons/widgets/model/LogisticRegression.svg",
  "NaiveBayes": "/icons/widgets/model/NaiveBayes.svg",
  "NN": "/icons/widgets/model/NN.svg",
  "PLS": "/icons/widgets/model/PLS.svg",
  "RandomForest": "/icons/widgets/model/RandomForest.svg",
  "SaveModel": "/icons/widgets/model/SaveModel.svg",
  "ScoringSheet": "/icons/widgets/model/ScoringSheet.svg",
  "SGD": "/icons/widgets/model/SGD.svg",
  "Stacking": "/icons/widgets/model/Stacking.svg",
  "SVM": "/icons/widgets/model/SVM.svg",
  "Tree": "/icons/widgets/model/Tree.svg",
  "UnivariateRegression": "/icons/widgets/model/UnivariateRegression.svg",

  // ===== unsupervised =====
  "Category-Unsupervised": "/icons/widgets/unsupervised/Category-Unsupervised.svg",
  "CorrespondenceAnalysis": "/icons/widgets/unsupervised/CorrespondenceAnalysis.svg",
  "DBSCAN": "/icons/widgets/unsupervised/DBSCAN.svg",
  "Distance": "/icons/widgets/unsupervised/Distance.svg",
  "DistanceFile": "/icons/widgets/unsupervised/DistanceFile.svg",
  "DistanceMap": "/icons/widgets/unsupervised/DistanceMap.svg",
  "DistanceMatrix": "/icons/widgets/unsupervised/DistanceMatrix.svg",
  "DistancesTransformation": "/icons/widgets/unsupervised/DistancesTransformation.svg",
  "HierarchicalClustering": "/icons/widgets/unsupervised/HierarchicalClustering.svg",
  "KMeans": "/icons/widgets/unsupervised/KMeans.svg",
  "LouvainClustering": "/icons/widgets/unsupervised/LouvainClustering.svg",
  "Manifold": "/icons/widgets/unsupervised/Manifold.svg",
  "MDS": "/icons/widgets/unsupervised/MDS.svg",
  "PCA": "/icons/widgets/unsupervised/PCA.svg",
  "SaveDistances": "/icons/widgets/unsupervised/SaveDistances.svg",
  "SOM": "/icons/widgets/unsupervised/SOM.svg",
  "TSNE": "/icons/widgets/unsupervised/TSNE.svg",

  // ===== visualize =====
  "BarPlot": "/icons/widgets/visualize/BarPlot.svg",
  "BoxPlot": "/icons/widgets/visualize/BoxPlot.svg",
  "Category-Visualize": "/icons/widgets/visualize/Category-Visualize.svg",
  "CN2RuleViewer": "/icons/widgets/visualize/CN2RuleViewer.svg",
  "Distribution": "/icons/widgets/visualize/Distribution.svg",
  "Freeviz": "/icons/widgets/visualize/Freeviz.svg",
  "Heatmap": "/icons/widgets/visualize/Heatmap.svg",
  "interval-horizontal": "/icons/widgets/visualize/interval-horizontal.svg",
  "interval-vertical": "/icons/widgets/visualize/interval-vertical.svg",
  "LinearProjection": "/icons/widgets/visualize/LinearProjection.svg",
  "LinePlot": "/icons/widgets/visualize/LinePlot.svg",
  "MosaicDisplay": "/icons/widgets/visualize/MosaicDisplay.svg",
  "Nomogram": "/icons/widgets/visualize/Nomogram.svg",
  "ParallelCoordinates": "/icons/widgets/visualize/ParallelCoordinates.svg",
  "PythagoreanForest": "/icons/widgets/visualize/PythagoreanForest.svg",
  "PythagoreanTree": "/icons/widgets/visualize/PythagoreanTree.svg",
  "Radviz": "/icons/widgets/visualize/Radviz.svg",
  "ScatterPlot": "/icons/widgets/visualize/ScatterPlot.svg",
  "ScoringSheetViewer": "/icons/widgets/visualize/ScoringSheetViewer.svg",
  "SieveDiagram": "/icons/widgets/visualize/SieveDiagram.svg",
  "SilhouettePlot": "/icons/widgets/visualize/SilhouettePlot.svg",
  "TreeViewer": "/icons/widgets/visualize/TreeViewer.svg",
  "VennDiagram": "/icons/widgets/visualize/VennDiagram.svg",
  "ViolinPlot": "/icons/widgets/visualize/ViolinPlot.svg",

};
